<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FTFlash</RootNamespace>
    <AssemblyName>FTFlash</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\app.ico" LogicalName="FTFlash.Assets.app.ico" />
    <EmbeddedResource Include="Assets\logo.png" LogicalName="FTFlash.Assets.logo.png" />
  </ItemGroup>

</Project>
